org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

mod_id=dolts_metadelights
mod_name=Dolt's Metadelights
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.dolthhaven.doltmetadelights

blueprint=8.1.0
fd=XTVZDOol
mnd=SGFJBL5q
dd=mAuzCOhP
mh=yabR7XEy
bnc=MbcR48Ou
runiclib=tk5EQpUG